### PR TITLE
Add 'moment' Option. (ex. 7 years ago )

### PR DESCRIPTION
**Pull request by finchMFG**
Adds 'moment' option. Outputs the largest measurement of time. ex:

```js
  return fromNow('Fri Sep 21 2011 13:51:39 GMT-0400 (Eastern Daylight Time)', {
    moment: true,
    ago: true,
  });
```
Outputs
`7 years ago`
Instead of
`7 years, 0 month, 6 days, 0 hour, 45 minutes ago`

Bonus: Add suffix for future dates. Ex:
```js
  return fromNow('Fri Sep 21 20119 13:51:39 GMT-0400 (Eastern Daylight Time)', {
    moment: true,
    ago: true,
  });
```
Outputs:
` 1 year from now`

### CODE REVIEW

**Comment by lukeed** [comment]
Hey, thanks!

For the first half, wouldn't this just be `max: 1`?

Also, I'd like to add the `from now` as a `opts.future` flag, since it (a) doesn't make sense to tie a future-based suffix to `"ago"` and (b) it would be breaking change to tie it to the same option.

**Comment by finchMFG** [comment]
Hi there! 

Using `max: 1` only outputs the year value. If the date falls within the current year, it will output `0 year` as it doesn't skip negative values. 'moment:true` only uses the largest measurement of time, so `0 years, 0 months, 2 days, 15 minutes` becomes `2 days`

Adding `from now` as a separate flag makes a lot of sense! I'll revise my PR. Cheers!

**Comment by lukeed** [comment]
Awesome, thank you!

It might be best if this PR only addresses the `future` flag. You inspired me to do a bunch of fixes 😜 Incorporating #5 and `max: 1` will apply the same functionality you're after~

**Comment by lukeed** [comment]
Hope you don't mind that I went ahead and took care of it. 

Thank you! 🙌

**Comment by finchMFG** [comment]
Looks great! Cheers :beers:

**Comment by lukeed** [comment]
`v3.0.0` is now out – I went with your original idea, but renamed `ago` to `suffix`

Thanks again for the contribution & instigating some changes :)

**Pull request merged**
